#ifndef MAME_MDISIMPLE_H
#define MAME_MDISIMPLE_H

#pragma once

#pragma pack(push, 1)

// TODO: ALL NUMBERS NATURALLY STORED AS LITTLE-ENDIAN ON WINDOWS AND
// MOST MODERN DESKTOP CPUS.  DO I NEED TO BE EXPLICIT ABOUT THIS?
// C:\GitHub\mame\src\osd\osdcomm.h

/* All mame debug info headers start with this */
typedef struct
{
	/* Must be "MDbI" to identify itself as a MAME debug info file */
	char magic[4];

	/* For now, only "simp" is supported */
	char type[4];

	unsigned char version;
} mame_debug_info_header_base;


/* mame's simple debug info format uses this as its complete header */
typedef struct
{
	mame_debug_info_header_base header_base;

	/* size in bytes of source_file_paths[][] */
	unsigned int source_file_paths_size;

	/* number of elements of line_mappings[] */
	unsigned int num_line_mappings;
} mame_debug_info_simple_header;


/* 
	A single mapping between a 1-based line number of a source file and the
	range of addresses containing the machine-language instructions
	generated by the line.  If a SET of lines generates a range of instructions,
	only the last line is represented.
*/
typedef struct
{
	/* address in CPU space of first byte of first instruction for this line */
	unsigned short address_first;

	/* address in CPU space of first byte of last instruction (inclusive) for this line */
	unsigned short address_last;

	/* 0-based index of source file (from source_file_paths) containing this line */
	unsigned short source_file_index;

	/* 1-based line number in source file */
	unsigned int line_number;
} mdi_line_mapping;


/*
	mame_debug_info_simple format:
	
	mame_debug_info_simple_header   header
	char                            source_file_paths[][]
	mdi_line_mapping                line_mappings[num_line_mappings]      

	Description:
	- Each source_file_paths[i] is a null-terminated string path to a source file.  The
	  first dimension index fits into an unsigned short.
	- line_mappings need not be in any order
	- At most one line_mappings entry per source file line number, and only for line numbers
	  corresponding to the first byte of a range of machine-language instruction.
	- No two line_mapping entries should have intersecting address ranges.
	- There is no compiler padding in these structures

*/

#pragma pack(pop)

#endif // MAME_MDISIMPLE_H